language: go
go:
- 1.8
- 1.9
- tip
services:
  - memcached
env:
  - MEMCACHED_HOSTS=localhost:11211
install:
- go get -t ./...
script:
- go vet ./...
- go test -v ./...
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_26c593b079d9_key -iv $encrypted_26c593b079d9_iv -in .gitcookies.enc -out .gitcookies -d || true'
after_success:
- go get github.com/mitchellh/gox
- gox -s "linux darwin windows freebsd solaris openbsd" -arch 'amd64 386 arm7 mips mips64' -osarch '!darwin/arm, !darwin/arm64'

